# Server settings
db:
  host:
  port:
  database:
  username:
  password:
production: false
server-name: "Hub"
default-scoreboard: true

# Options
welcome-message: "&aWelcome to &b&lGalaxy Parks&a!"
gamemode: "ADVENTURE"
hotbar-tools: true
inventory-sync: false